version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: moph-notify-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: root123
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: moph_notify_aranhos
      TZ: 'Asia/Bangkok'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moph-network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-proot123']
      timeout: 20s
      retries: 10
      interval: 10s

volumes:
  mysql_data:
    driver: local

networks:
  moph-network:
    driver: bridge
